### ISSUE TITLE
如何将resource和app独立？

### ISSUE THREAD

**Issue by EeyoreLee** [EeyoreLee/microservices-framework#5]
当我使用gunicorn启动app时，resource中的对象随着app扩展成多线程，我将深度学习模型放在resource中，当我gunicorn的workers设置为4时，我的模型也固定变为4个，从而消耗了4倍的显存。有什么办法当workers为4的时候，模型可以设置为3或5，并让线程随机访问到某个模型副本，同时我可以自定义随机策略来完成线程和模型的负载均衡？  
下面是我的app文件和gunicorn文件 
```
config = {
    'NODE_CONF': NODE_CONF,
    'PATH_CONF': PATH_CONF
}
resource = {}  
resource['dfa'] = init_dfa()  
resource["lock"] = False  
engine = Engine(config, resource, name='detection')  
engine.response_package = response_package_v1  
app = engine.app
```
可以看作`init_dfa()`返回了一个我自定义的对象，有时它是我的模型
```
bind = ["0.0.0.0:41000"]
worker_class = "gevent"
workers = 4
backlog = 2048
pidfile = "log/gunicorn.pid"
accesslog = "log/access.log"
errorlog = "log/debug.log"
timeout = 600
debug=False
capture_output = True
```

**Comment by mirrornight** [comment]
https://github.com/benoitc/gunicorn/issues/1026

**Comment by EeyoreLee** [comment]
This is a demo for this issue. https://github.com/EeyoreLee/msf-issue-demo_5
